version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: godlife
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis-master:
    image: redis:6.2
    container_name: redis_master
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master:/usr/local/etc/redis
      - redis_master_data:/data

  redis-slave1:
    image: redis:6.2
    container_name: redis_slave1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--slaveof", "redis_master", "6379"]
    ports:
      - "6380:6379"
    volumes:
      - ./redis-slave1:/usr/local/etc/redis
      - redis_slave1_data:/data

  redis-slave2:
    image: redis:6.2
    container_name: redis_slave2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--slaveof", "redis_master", "6379"]
    ports:
      - "6381:6379"
    volumes:
      - ./redis-slave2:/usr/local/etc/redis
      - redis_slave2_data:/data

  redis-sentinel:
    image: redis:6.2
    container_name: redis_sentinel
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel:/usr/local/etc/redis

volumes:
  mysql_data:
  redis_master_data:
  redis_slave1_data:
  redis_slave2_data:
